/*!Peripheral access API for HPM5301 microcontrollers (generated using svd2rust v0.37.1 ( ))

You can find an overview of the generated API [here].

API features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.

[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api
[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased
[repository]: https://github.com/rust-embedded/svd2rust*/
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unsafe_op_in_unsafe_fn)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
///Number available in the NVIC for configuring priority
pub const NVIC_PRIO_BITS: u8 = 7;
#[allow(unused_imports)]
use generic::*;
///Common register and bit access and modify traits
pub mod generic;
#[cfg(feature = "rt")]
unsafe extern "C" {}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    pub _handler: unsafe extern "C" fn(),
    pub _reserved: usize,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[unsafe(no_mangle)]
pub static __EXTERNAL_INTERRUPTS: [Vector; 0] = [];
///FGPIO
pub type Fgpio = crate::Periph<fgpio::RegisterBlock, 0x000c_0000>;
impl core::fmt::Debug for Fgpio {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Fgpio").finish()
    }
}
///FGPIO
pub mod fgpio;
///GPIO0
pub type Gpio0 = crate::Periph<fgpio::RegisterBlock, 0xf00d_0000>;
impl core::fmt::Debug for Gpio0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio0").finish()
    }
}
///GPIO0
pub use self::fgpio as gpio0;
///PGPIO
pub type Pgpio = crate::Periph<fgpio::RegisterBlock, 0xf411_c000>;
impl core::fmt::Debug for Pgpio {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pgpio").finish()
    }
}
///PGPIO
pub use self::fgpio as pgpio;
///PLIC
pub type Plic = crate::Periph<plic::RegisterBlock, 0xe400_0000>;
impl core::fmt::Debug for Plic {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Plic").finish()
    }
}
///PLIC
pub mod plic;
///MCHTMR
pub type Mchtmr = crate::Periph<mchtmr::RegisterBlock, 0xe600_0000>;
impl core::fmt::Debug for Mchtmr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mchtmr").finish()
    }
}
///MCHTMR
pub mod mchtmr;
///PLICSW
pub type Plicsw = crate::Periph<plicsw::RegisterBlock, 0xe640_0000>;
impl core::fmt::Debug for Plicsw {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Plicsw").finish()
    }
}
///PLICSW
pub mod plicsw;
///GPTMR0
pub type Gptmr0 = crate::Periph<gptmr0::RegisterBlock, 0xf000_0000>;
impl core::fmt::Debug for Gptmr0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gptmr0").finish()
    }
}
///GPTMR0
pub mod gptmr0;
///GPTMR1
pub type Gptmr1 = crate::Periph<gptmr0::RegisterBlock, 0xf000_4000>;
impl core::fmt::Debug for Gptmr1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gptmr1").finish()
    }
}
///GPTMR1
pub use self::gptmr0 as gptmr1;
///PTMR
pub type Ptmr = crate::Periph<gptmr0::RegisterBlock, 0xf412_0000>;
impl core::fmt::Debug for Ptmr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ptmr").finish()
    }
}
///PTMR
pub use self::gptmr0 as ptmr;
///UART0
pub type Uart0 = crate::Periph<uart0::RegisterBlock, 0xf004_0000>;
impl core::fmt::Debug for Uart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart0").finish()
    }
}
///UART0
pub mod uart0;
///UART1
pub type Uart1 = crate::Periph<uart0::RegisterBlock, 0xf004_4000>;
impl core::fmt::Debug for Uart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart1").finish()
    }
}
///UART1
pub use self::uart0 as uart1;
///UART2
pub type Uart2 = crate::Periph<uart0::RegisterBlock, 0xf004_8000>;
impl core::fmt::Debug for Uart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart2").finish()
    }
}
///UART2
pub use self::uart0 as uart2;
///UART3
pub type Uart3 = crate::Periph<uart0::RegisterBlock, 0xf004_c000>;
impl core::fmt::Debug for Uart3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart3").finish()
    }
}
///UART3
pub use self::uart0 as uart3;
///PUART
pub type Puart = crate::Periph<uart0::RegisterBlock, 0xf412_4000>;
impl core::fmt::Debug for Puart {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Puart").finish()
    }
}
///PUART
pub use self::uart0 as puart;
///I2C0
pub type I2c0 = crate::Periph<i2c0::RegisterBlock, 0xf006_0000>;
impl core::fmt::Debug for I2c0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c0").finish()
    }
}
///I2C0
pub mod i2c0;
///I2C1
pub type I2c1 = crate::Periph<i2c0::RegisterBlock, 0xf006_4000>;
impl core::fmt::Debug for I2c1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c1").finish()
    }
}
///I2C1
pub use self::i2c0 as i2c1;
///I2C2
pub type I2c2 = crate::Periph<i2c0::RegisterBlock, 0xf006_8000>;
impl core::fmt::Debug for I2c2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c2").finish()
    }
}
///I2C2
pub use self::i2c0 as i2c2;
///I2C3
pub type I2c3 = crate::Periph<i2c0::RegisterBlock, 0xf006_c000>;
impl core::fmt::Debug for I2c3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c3").finish()
    }
}
///I2C3
pub use self::i2c0 as i2c3;
///SPI0
pub type Spi0 = crate::Periph<spi0::RegisterBlock, 0xf007_0000>;
impl core::fmt::Debug for Spi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi0").finish()
    }
}
///SPI0
pub mod spi0;
///SPI1
pub type Spi1 = crate::Periph<spi0::RegisterBlock, 0xf007_4000>;
impl core::fmt::Debug for Spi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi1").finish()
    }
}
///SPI1
pub use self::spi0 as spi1;
///SPI2
pub type Spi2 = crate::Periph<spi0::RegisterBlock, 0xf007_8000>;
impl core::fmt::Debug for Spi2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi2").finish()
    }
}
///SPI2
pub use self::spi0 as spi2;
///SPI3
pub type Spi3 = crate::Periph<spi0::RegisterBlock, 0xf007_c000>;
impl core::fmt::Debug for Spi3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi3").finish()
    }
}
///SPI3
pub use self::spi0 as spi3;
///CRC
pub type Crc = crate::Periph<crc::RegisterBlock, 0xf008_0000>;
impl core::fmt::Debug for Crc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crc").finish()
    }
}
///CRC
pub mod crc;
///TSNS
pub type Tsns = crate::Periph<tsns::RegisterBlock, 0xf009_0000>;
impl core::fmt::Debug for Tsns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tsns").finish()
    }
}
///TSNS
pub mod tsns;
///MBX0A
pub type Mbx0a = crate::Periph<mbx0a::RegisterBlock, 0xf00a_0000>;
impl core::fmt::Debug for Mbx0a {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mbx0a").finish()
    }
}
///MBX0A
pub mod mbx0a;
///MBX0B
pub type Mbx0b = crate::Periph<mbx0a::RegisterBlock, 0xf00a_4000>;
impl core::fmt::Debug for Mbx0b {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mbx0b").finish()
    }
}
///MBX0B
pub use self::mbx0a as mbx0b;
///EWDG0
pub type Ewdg0 = crate::Periph<ewdg0::RegisterBlock, 0xf00b_0000>;
impl core::fmt::Debug for Ewdg0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ewdg0").finish()
    }
}
///EWDG0
pub mod ewdg0;
///EWDG1
pub type Ewdg1 = crate::Periph<ewdg0::RegisterBlock, 0xf00b_4000>;
impl core::fmt::Debug for Ewdg1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ewdg1").finish()
    }
}
///EWDG1
pub use self::ewdg0 as ewdg1;
///PEWDG
pub type Pewdg = crate::Periph<ewdg0::RegisterBlock, 0xf412_8000>;
impl core::fmt::Debug for Pewdg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pewdg").finish()
    }
}
///PEWDG
pub use self::ewdg0 as pewdg;
///DMAMUX
pub type Dmamux = crate::Periph<dmamux::RegisterBlock, 0xf00c_4000>;
impl core::fmt::Debug for Dmamux {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmamux").finish()
    }
}
///DMAMUX
pub mod dmamux;
///HDMA
pub type Hdma = crate::Periph<hdma::RegisterBlock, 0xf00c_8000>;
impl core::fmt::Debug for Hdma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Hdma").finish()
    }
}
///HDMA
pub mod hdma;
///GPIOM
pub type Gpiom = crate::Periph<gpiom::RegisterBlock, 0xf00d_8000>;
impl core::fmt::Debug for Gpiom {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiom").finish()
    }
}
///GPIOM
pub mod gpiom;
///SYNT
pub type Synt = crate::Periph<synt::RegisterBlock, 0xf032_8000>;
impl core::fmt::Debug for Synt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Synt").finish()
    }
}
///SYNT
pub mod synt;
///TRGM0
pub type Trgm0 = crate::Periph<trgm0::RegisterBlock, 0xf033_c000>;
impl core::fmt::Debug for Trgm0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Trgm0").finish()
    }
}
///TRGM0
pub mod trgm0;
///USB0
pub type Usb0 = crate::Periph<usb0::RegisterBlock, 0xf300_c000>;
impl core::fmt::Debug for Usb0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usb0").finish()
    }
}
///USB0
pub mod usb0;
///SEC
pub type Sec = crate::Periph<sec::RegisterBlock, 0xf304_4000>;
impl core::fmt::Debug for Sec {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sec").finish()
    }
}
///SEC
pub mod sec;
///MON
pub type Mon = crate::Periph<mon::RegisterBlock, 0xf304_8000>;
impl core::fmt::Debug for Mon {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mon").finish()
    }
}
///MON
pub mod mon;
///OTP
pub type Otp = crate::Periph<otp::RegisterBlock, 0xf305_0000>;
impl core::fmt::Debug for Otp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Otp").finish()
    }
}
///OTP
pub mod otp;
///KEYM
pub type Keym = crate::Periph<keym::RegisterBlock, 0xf305_4000>;
impl core::fmt::Debug for Keym {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Keym").finish()
    }
}
///KEYM
pub mod keym;
///ADC0
pub type Adc0 = crate::Periph<adc0::RegisterBlock, 0xf308_0000>;
impl core::fmt::Debug for Adc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc0").finish()
    }
}
///ADC0
pub mod adc0;
///ACMP
pub type Acmp = crate::Periph<acmp::RegisterBlock, 0xf30b_0000>;
impl core::fmt::Debug for Acmp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Acmp").finish()
    }
}
///ACMP
pub mod acmp;
///SYSCTL
pub type Sysctl = crate::Periph<sysctl::RegisterBlock, 0xf400_0000>;
impl core::fmt::Debug for Sysctl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sysctl").finish()
    }
}
///SYSCTL
pub mod sysctl;
///IOC
pub type Ioc = crate::Periph<ioc::RegisterBlock, 0xf404_0000>;
impl core::fmt::Debug for Ioc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ioc").finish()
    }
}
///IOC
pub mod ioc;
///PIOC
pub type Pioc = crate::Periph<ioc::RegisterBlock, 0xf411_8000>;
impl core::fmt::Debug for Pioc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pioc").finish()
    }
}
///PIOC
pub use self::ioc as pioc;
///PLLCTLV2
pub type Pllctlv2 = crate::Periph<pllctlv2::RegisterBlock, 0xf40c_0000>;
impl core::fmt::Debug for Pllctlv2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pllctlv2").finish()
    }
}
///PLLCTLV2
pub mod pllctlv2;
///PPOR
pub type Ppor = crate::Periph<ppor::RegisterBlock, 0xf410_0000>;
impl core::fmt::Debug for Ppor {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ppor").finish()
    }
}
///PPOR
pub mod ppor;
///PCFG
pub type Pcfg = crate::Periph<pcfg::RegisterBlock, 0xf410_4000>;
impl core::fmt::Debug for Pcfg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pcfg").finish()
    }
}
///PCFG
pub mod pcfg;
///PGPR0
pub type Pgpr0 = crate::Periph<pgpr0::RegisterBlock, 0xf411_0000>;
impl core::fmt::Debug for Pgpr0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pgpr0").finish()
    }
}
///PGPR0
pub mod pgpr0;
///PGPR1
pub type Pgpr1 = crate::Periph<pgpr0::RegisterBlock, 0xf411_4000>;
impl core::fmt::Debug for Pgpr1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pgpr1").finish()
    }
}
///PGPR1
pub use self::pgpr0 as pgpr1;
///PDGO
pub type Pdgo = crate::Periph<pdgo::RegisterBlock, 0xf413_4000>;
impl core::fmt::Debug for Pdgo {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pdgo").finish()
    }
}
///PDGO
pub mod pdgo;
#[unsafe(no_mangle)]
static mut DEVICE_PERIPHERALS: bool = false;
/// All the peripherals.
#[allow(non_snake_case)]
pub struct Peripherals {
    ///FGPIO
    pub fgpio: Fgpio,
    ///GPIO0
    pub gpio0: Gpio0,
    ///PGPIO
    pub pgpio: Pgpio,
    ///PLIC
    pub plic: Plic,
    ///MCHTMR
    pub mchtmr: Mchtmr,
    ///PLICSW
    pub plicsw: Plicsw,
    ///GPTMR0
    pub gptmr0: Gptmr0,
    ///GPTMR1
    pub gptmr1: Gptmr1,
    ///PTMR
    pub ptmr: Ptmr,
    ///UART0
    pub uart0: Uart0,
    ///UART1
    pub uart1: Uart1,
    ///UART2
    pub uart2: Uart2,
    ///UART3
    pub uart3: Uart3,
    ///PUART
    pub puart: Puart,
    ///I2C0
    pub i2c0: I2c0,
    ///I2C1
    pub i2c1: I2c1,
    ///I2C2
    pub i2c2: I2c2,
    ///I2C3
    pub i2c3: I2c3,
    ///SPI0
    pub spi0: Spi0,
    ///SPI1
    pub spi1: Spi1,
    ///SPI2
    pub spi2: Spi2,
    ///SPI3
    pub spi3: Spi3,
    ///CRC
    pub crc: Crc,
    ///TSNS
    pub tsns: Tsns,
    ///MBX0A
    pub mbx0a: Mbx0a,
    ///MBX0B
    pub mbx0b: Mbx0b,
    ///EWDG0
    pub ewdg0: Ewdg0,
    ///EWDG1
    pub ewdg1: Ewdg1,
    ///PEWDG
    pub pewdg: Pewdg,
    ///DMAMUX
    pub dmamux: Dmamux,
    ///HDMA
    pub hdma: Hdma,
    ///GPIOM
    pub gpiom: Gpiom,
    ///SYNT
    pub synt: Synt,
    ///TRGM0
    pub trgm0: Trgm0,
    ///USB0
    pub usb0: Usb0,
    ///SEC
    pub sec: Sec,
    ///MON
    pub mon: Mon,
    ///OTP
    pub otp: Otp,
    ///KEYM
    pub keym: Keym,
    ///ADC0
    pub adc0: Adc0,
    ///ACMP
    pub acmp: Acmp,
    ///SYSCTL
    pub sysctl: Sysctl,
    ///IOC
    pub ioc: Ioc,
    ///PIOC
    pub pioc: Pioc,
    ///PLLCTLV2
    pub pllctlv2: Pllctlv2,
    ///PPOR
    pub ppor: Ppor,
    ///PCFG
    pub pcfg: Pcfg,
    ///PGPR0
    pub pgpr0: Pgpr0,
    ///PGPR1
    pub pgpr1: Pgpr1,
    ///PDGO
    pub pdgo: Pdgo,
}
impl Peripherals {
    /// Returns all the peripherals *once*.
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    /// Unchecked version of `Peripherals::take`.
    ///
    /// # Safety
    ///
    /// Each of the returned peripherals must be used at most once.
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            fgpio: Fgpio::steal(),
            gpio0: Gpio0::steal(),
            pgpio: Pgpio::steal(),
            plic: Plic::steal(),
            mchtmr: Mchtmr::steal(),
            plicsw: Plicsw::steal(),
            gptmr0: Gptmr0::steal(),
            gptmr1: Gptmr1::steal(),
            ptmr: Ptmr::steal(),
            uart0: Uart0::steal(),
            uart1: Uart1::steal(),
            uart2: Uart2::steal(),
            uart3: Uart3::steal(),
            puart: Puart::steal(),
            i2c0: I2c0::steal(),
            i2c1: I2c1::steal(),
            i2c2: I2c2::steal(),
            i2c3: I2c3::steal(),
            spi0: Spi0::steal(),
            spi1: Spi1::steal(),
            spi2: Spi2::steal(),
            spi3: Spi3::steal(),
            crc: Crc::steal(),
            tsns: Tsns::steal(),
            mbx0a: Mbx0a::steal(),
            mbx0b: Mbx0b::steal(),
            ewdg0: Ewdg0::steal(),
            ewdg1: Ewdg1::steal(),
            pewdg: Pewdg::steal(),
            dmamux: Dmamux::steal(),
            hdma: Hdma::steal(),
            gpiom: Gpiom::steal(),
            synt: Synt::steal(),
            trgm0: Trgm0::steal(),
            usb0: Usb0::steal(),
            sec: Sec::steal(),
            mon: Mon::steal(),
            otp: Otp::steal(),
            keym: Keym::steal(),
            adc0: Adc0::steal(),
            acmp: Acmp::steal(),
            sysctl: Sysctl::steal(),
            ioc: Ioc::steal(),
            pioc: Pioc::steal(),
            pllctlv2: Pllctlv2::steal(),
            ppor: Ppor::steal(),
            pcfg: Pcfg::steal(),
            pgpr0: Pgpr0::steal(),
            pgpr1: Pgpr1::steal(),
            pdgo: Pdgo::steal(),
        }
    }
}
